### ISSUE TITLE
Errors Installing on macOS Mojave

### ISSUE THREAD

**Issue by anuraag94** [LeeKamentsky/python-javabridge#169]
Unlike https://github.com/LeeKamentsky/python-javabridge/issues/159 I'm having trouble installing on macOS Mojave, and they're similar Java version 6 errors.

When I issue 
`pip install javabridge`

I get these errors

```
Collecting javabridge
Using cached https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz
Requirement already satisfied: numpy in /anaconda3/lib/python3.7/site-packages (from javabridge) (1.16.4)
Building wheels for collected packages: javabridge
  Building wheel for javabridge (setup.py) ... error
  ERROR: Complete output from command //anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/bj/ms7nqbw15jscjflgsj80mzpw0000gn/T/pip-install-zt2rec1z/javabridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bj/ms7nqbw15jscjflgsj80mzpw0000gn/T/pip-wheel-jbx1a39y --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/javabridge
  copying javabridge/_version.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
  copying javabridge/jutil.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
  copying javabridge/locate.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
  copying javabridge/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
  copying javabridge/wrappers.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
  copying javabridge/noseplugin.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
  creating build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
  copying javabridge/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_cpython.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_javabridge.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_jutil.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
  copying javabridge/tests/test_wrappers.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
  creating build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
  copying javabridge/jars/rhino-1.7R4.jar -> build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
  copying javabridge/jars/runnablequeue.jar -> build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
  copying javabridge/jars/cpython.jar -> build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
  copying javabridge/jars/test.jar -> build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
  running build_ext
  javac -source 6 -target 6 /private/var/folders/bj/ms7nqbw15jscjflgsj80mzpw0000gn/T/pip-install-zt2rec1z/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
  warning: [options] bootstrap class path not set in conjunction with -source 6
  error: Source option 6 is no longer supported. Use 7 or later.
  error: Target option 6 is no longer supported. Use 7 or later.
  error: command 'javac' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for javabridge
  Running setup.py clean for javabridge
Failed to build javabridge
Installing collected packages: javabridge
  Running setup.py install for javabridge ... error
    ERROR: Complete output from command //anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/bj/ms7nqbw15jscjflgsj80mzpw0000gn/T/pip-install-zt2rec1z/javabridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bj/ms7nqbw15jscjflgsj80mzpw0000gn/T/pip-record-lccr6io3/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/javabridge
    copying javabridge/_version.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
    copying javabridge/jutil.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
    copying javabridge/locate.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
    copying javabridge/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
    copying javabridge/wrappers.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
    copying javabridge/noseplugin.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
    creating build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
    copying javabridge/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_cpython.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_javabridge.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_jutil.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_wrappers.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
    creating build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
    copying javabridge/jars/rhino-1.7R4.jar -> build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
    copying javabridge/jars/runnablequeue.jar -> build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
    copying javabridge/jars/cpython.jar -> build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
    copying javabridge/jars/test.jar -> build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
    running build_ext
    javac -source 6 -target 6 /private/var/folders/bj/ms7nqbw15jscjflgsj80mzpw0000gn/T/pip-install-zt2rec1z/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    error: Source option 6 is no longer supported. Use 7 or later.
    error: Target option 6 is no longer supported. Use 7 or later.
    error: command 'javac' failed with exit status 2
    ----------------------------------------
ERROR: Command "//anaconda3/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/bj/ms7nqbw15jscjflgsj80mzpw0000gn/T/pip-install-zt2rec1z/javabridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bj/ms7nqbw15jscjflgsj80mzpw0000gn/T/pip-record-lccr6io3/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/bj/ms7nqbw15jscjflgsj80mzpw0000gn/T/pip-install-zt2rec1z/javabridge/
```

'/usr/libexec/java_home' reports

`/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home`

'java -version' reports

`java version "13" 2019-09-17
Java(TM) SE Runtime Environment (build 13+33)
Java HotSpot(TM) 64-Bit Server VM (build 13+33, mixed mode, sharing)`

'echo $JAVA_HOME' reports:

`/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home`

Then running 'python setup.py install' yields:

```
running install
running bdist_egg
running egg_info
creating javabridge.egg-info
writing javabridge.egg-info/PKG-INFO
writing dependency_links to javabridge.egg-info/dependency_links.txt
writing entry points to javabridge.egg-info/entry_points.txt
writing requirements to javabridge.egg-info/requires.txt
writing top-level names to javabridge.egg-info/top_level.txt
writing manifest file 'javabridge.egg-info/SOURCES.txt'
reading manifest file 'javabridge.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '_javabridge.c'
warning: no files found matching '_javabridge_mac.c'
warning: no files found matching '_javabridge_nomac.c'
no previously-included directories found matching '*.pyx'
writing manifest file 'javabridge.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.7-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.macosx-10.7-x86_64-3.7
creating build/lib.macosx-10.7-x86_64-3.7/javabridge
copying javabridge/_version.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
copying javabridge/jutil.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
copying javabridge/locate.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
copying javabridge/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
copying javabridge/wrappers.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
copying javabridge/noseplugin.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge
creating build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
copying javabridge/tests/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
copying javabridge/tests/test_cpython.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
copying javabridge/tests/test_javabridge.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
copying javabridge/tests/test_jutil.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
copying javabridge/tests/test_wrappers.py -> build/lib.macosx-10.7-x86_64-3.7/javabridge/tests
creating build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
copying javabridge/jars/rhino-1.7R4.jar -> build/lib.macosx-10.7-x86_64-3.7/javabridge/jars
running build_ext
javac java/org/cellprofiler/runnablequeue/RunnableQueue.java
jar cf build/lib.macosx-10.7-x86_64-3.7/javabridge/jars/runnablequeue.jar -C java org/cellprofiler/runnablequeue/RunnableQueue.class -C java org/cellprofiler/runnablequeue/RunnableQueue$1.class
javac java/org/cellprofiler/javabridge/test/RealRect.java
jar cf build/lib.macosx-10.7-x86_64-3.7/javabridge/jars/test.jar -C java org/cellprofiler/javabridge/test/RealRect.class
javac java/org/cellprofiler/javabridge/CPython.java java/org/cellprofiler/javabridge/CPythonInvocationHandler.java
Note: java/org/cellprofiler/javabridge/CPythonInvocationHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
jar cf build/lib.macosx-10.7-x86_64-3.7/javabridge/jars/cpython.jar -C java org/cellprofiler/javabridge/CPythonInvocationHandler.class -C java org/cellprofiler/javabridge/CPython.class -C java org/cellprofiler/javabridge/CPython$WrappedException.class -C java org/cellprofiler/javabridge/CPython$StackFrame.class -C java org/cellprofiler/javabridge/CPythonInvocationHandler.class
warning: _javabridge_osspecific.pxd:12:4: 'JavaVMOption' redeclared 
warning: _javabridge_osspecific.pxd:19:4: 'JavaVMInitArgs' redeclared 
warning: _javabridge.pyx:94:4: 'jvalue' redeclared 
warning: _javabridge.pyx:112:4: 'JavaVMOption' redeclared 
warning: _javabridge.pyx:119:4: 'JavaVMInitArgs' redeclared 
warning: _javabridge_osspecific.pxd:12:4: 'JavaVMOption' redeclared 
warning: _javabridge_osspecific.pxd:19:4: 'JavaVMInitArgs' redeclared 
warning: _javabridge_mac.pyx:4:4: 'jint' redeclared 
warning: _javabridge_mac.pyx:5:4: 'jboolean' redeclared 
warning: _javabridge_mac.pyx:9:4: 'JavaVM' redeclared 
warning: _javabridge_mac.pyx:14:4: 'JavaVMOption' redeclared 
warning: _javabridge_mac.pyx:21:4: 'JavaVMInitArgs' redeclared 
warning: _javabridge_nomac.pxd:15:4: 'JavaVMInitArgs' redeclared 
warning: _javabridge_nomac.pxd:20:4: 'JavaVMOption' redeclared 
warning: _javabridge_nomac.pyx:4:4: 'jint' redeclared 
warning: _javabridge_nomac.pyx:5:4: 'jboolean' redeclared 
warning: _javabridge_nomac.pyx:9:4: 'JavaVM' redeclared 
building 'javabridge._javabridge' extension
creating build/temp.macosx-10.7-x86_64-3.7
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda3/include -arch x86_64 -I//anaconda3/include -arch x86_64 -I/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/include/darwin -I//anaconda3/lib/python3.7/site-packages/numpy/core/include -I//anaconda3/include/python3.7m -c _javabridge.c -o build/temp.macosx-10.7-x86_64-3.7/_javabridge.o
In file included from _javabridge.c:598:
In file included from //anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from //anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from //anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824:
//anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy
      API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
In file included from _javabridge.c:601:
./mac_javabridge_utils.h:47:25: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacStopVM();
                        ^
                         void
./mac_javabridge_utils.h:55:30: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacRunLoopInit();
                             ^
                              void
./mac_javabridge_utils.h:63:29: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacRunLoopRun();
                            ^
                             void
./mac_javabridge_utils.h:71:31: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacRunLoopReset();
                              ^
                               void
./mac_javabridge_utils.h:79:30: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacStopRunLoop();
                             ^
                              void
./mac_javabridge_utils.h:88:30: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT int MacIsMainThread();
                             ^
                              void
./mac_javabridge_utils.h:103:20: warning: this function declaration is not a prototype [-Wstrict-prototypes]
void MacRunLoopStop();
                   ^
                    void
_javabridge.c:8122:36: warning: implicit declaration of function 'CreateJavaVM' is invalid in C99 [-Wimplicit-function-declaration]
  __pyx_t_3 = __Pyx_PyInt_From_int(CreateJavaVM((&__pyx_v_self->vm), ((void **)(&__pyx_v_env)), (&__pyx_v_args))); if (unli...
                                   ^
_javabridge.c:8122:36: warning: this function declaration is not a prototype [-Wstrict-prototypes]
_javabridge.c:9199:5: warning: implicit declaration of function 'StopVM' is invalid in C99 [-Wimplicit-function-declaration]
    StopVM(__pyx_v_self->vm);
    ^
_javabridge.c:9199:5: warning: this function declaration is not a prototype [-Wstrict-prototypes]
_javabridge.c:29699:3: warning: incompatible pointer to integer conversion returning 'void *' from a function with result type
      'int' [-Wint-conversion]
  import_array();
  ^~~~~~~~~~~~~~
//anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1546:151: note: expanded from macro
      'import_array'
  ...PyErr_SetString(PyExc_ImportError, "numpy.core.multiarray failed to import"); return NUMPY_IMPORT_ARRAY_RETVAL; } }
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
//anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/__multiarray_api.h:1541:35: note: expanded from macro
      'NUMPY_IMPORT_ARRAY_RETVAL'
#define NUMPY_IMPORT_ARRAY_RETVAL NULL
                                  ^~~~
/Library/Developer/CommandLineTools/usr/lib/clang/10.0.1/include/stddef.h:105:16: note: expanded from macro 'NULL'
#  define NULL ((void*)0)
               ^~~~~~~~~~
_javabridge.c:33235:26: warning: code will never be executed [-Wunreachable-code]
                module = PyImport_ImportModuleLevelObject(
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
14 warnings generated.
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda3/include -arch x86_64 -I//anaconda3/include -arch x86_64 -I/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/include/darwin -I//anaconda3/lib/python3.7/site-packages/numpy/core/include -I//anaconda3/include/python3.7m -c _javabridge_mac.c -o build/temp.macosx-10.7-x86_64-3.7/_javabridge_mac.o
In file included from _javabridge_mac.c:597:
./mac_javabridge_utils.h:47:25: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacStopVM();
                        ^
                         void
./mac_javabridge_utils.h:55:30: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacRunLoopInit();
                             ^
                              void
./mac_javabridge_utils.h:63:29: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacRunLoopRun();
                            ^
                             void
./mac_javabridge_utils.h:71:31: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacRunLoopReset();
                              ^
                               void
./mac_javabridge_utils.h:79:30: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT void MacStopRunLoop();
                             ^
                              void
./mac_javabridge_utils.h:88:30: warning: this function declaration is not a prototype [-Wstrict-prototypes]
JNIEXPORT int MacIsMainThread();
                             ^
                              void
./mac_javabridge_utils.h:103:20: warning: this function declaration is not a prototype [-Wstrict-prototypes]
void MacRunLoopStop();
                   ^
                    void
7 warnings generated.
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda3/include -arch x86_64 -I//anaconda3/include -arch x86_64 -I/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/include/darwin -I//anaconda3/lib/python3.7/site-packages/numpy/core/include -I//anaconda3/include/python3.7m -c mac_javabridge_utils.c -o build/temp.macosx-10.7-x86_64-3.7/mac_javabridge_utils.o
mac_javabridge_utils.c:112:11: warning: unused variable 'retval' [-Wunused-variable]
    void *retval;
          ^
mac_javabridge_utils.c:176:16: warning: unused variable 'exception' [-Wunused-variable]
    jthrowable exception;
               ^
mac_javabridge_utils.c:321:30: warning: unused variable 'observerRef' [-Wunused-variable]
    CFRunLoopObserverRef     observerRef;
                             ^
mac_javabridge_utils.c:320:30: warning: unused variable 'observerContext' [-Wunused-variable]
    CFRunLoopObserverContext observerContext;
                             ^
mac_javabridge_utils.c:294:13: warning: unused function 'CBObserve' [-Wunused-function]
static void CBObserve(CFRunLoopObserverRef observer, 
            ^
5 warnings generated.
gcc -bundle -undefined dynamic_lookup -L//anaconda3/lib -arch x86_64 -L//anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/_javabridge.o build/temp.macosx-10.7-x86_64-3.7/_javabridge_mac.o build/temp.macosx-10.7-x86_64-3.7/mac_javabridge_utils.o -o build/lib.macosx-10.7-x86_64-3.7/javabridge/_javabridge.cpython-37m-darwin.so
building java2cpython library
creating build/temp.macosx-10.7-x86_64-3.7/java
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I//anaconda3/include -arch x86_64 -I//anaconda3/include -arch x86_64 -I//anaconda3/include/python3.7m -Ijava -I/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk-13.jdk/Contents/Home/include/darwin -I//anaconda3/lib/python3.7/site-packages/numpy/core/include -I//anaconda3/include/python3.7m -c java/org_cellprofiler_javabridge_CPython.c -o build/temp.macosx-10.7-x86_64-3.7/java/org_cellprofiler_javabridge_CPython.o
gcc -bundle -undefined dynamic_lookup -L//anaconda3/lib -arch x86_64 -L//anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/java/org_cellprofiler_javabridge_CPython.o -L//anaconda3/lib -o build/lib.macosx-10.7-x86_64-3.7/javabridge/jars/libjava2cpython.jnilib
creating build/bdist.macosx-10.7-x86_64
creating build/bdist.macosx-10.7-x86_64/egg
creating build/bdist.macosx-10.7-x86_64/egg/javabridge
creating build/bdist.macosx-10.7-x86_64/egg/javabridge/jars
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/jars/rhino-1.7R4.jar -> build/bdist.macosx-10.7-x86_64/egg/javabridge/jars
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/jars/runnablequeue.jar -> build/bdist.macosx-10.7-x86_64/egg/javabridge/jars
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/jars/cpython.jar -> build/bdist.macosx-10.7-x86_64/egg/javabridge/jars
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/jars/test.jar -> build/bdist.macosx-10.7-x86_64/egg/javabridge/jars
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/jars/libjava2cpython.jnilib -> build/bdist.macosx-10.7-x86_64/egg/javabridge/jars
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/_version.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/jutil.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/locate.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge
creating build/bdist.macosx-10.7-x86_64/egg/javabridge/tests
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/tests/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge/tests
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/tests/test_cpython.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge/tests
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/tests/test_javabridge.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge/tests
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/tests/test_jutil.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge/tests
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/tests/test_wrappers.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge/tests
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/__init__.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/wrappers.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/_javabridge.cpython-37m-darwin.so -> build/bdist.macosx-10.7-x86_64/egg/javabridge
copying build/lib.macosx-10.7-x86_64-3.7/javabridge/noseplugin.py -> build/bdist.macosx-10.7-x86_64/egg/javabridge
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/_version.py to _version.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/jutil.py to jutil.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/locate.py to locate.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/tests/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/tests/test_cpython.py to test_cpython.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/tests/test_javabridge.py to test_javabridge.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/tests/test_jutil.py to test_jutil.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/tests/test_wrappers.py to test_wrappers.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/wrappers.py to wrappers.cpython-37.pyc
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/noseplugin.py to noseplugin.cpython-37.pyc
creating stub loader for javabridge/_javabridge.cpython-37m-darwin.so
byte-compiling build/bdist.macosx-10.7-x86_64/egg/javabridge/_javabridge.py to _javabridge.cpython-37.pyc
creating build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying javabridge.egg-info/PKG-INFO -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying javabridge.egg-info/SOURCES.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying javabridge.egg-info/dependency_links.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying javabridge.egg-info/entry_points.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying javabridge.egg-info/requires.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
copying javabridge.egg-info/top_level.txt -> build/bdist.macosx-10.7-x86_64/egg/EGG-INFO
writing build/bdist.macosx-10.7-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
javabridge.__pycache__.__init__.cpython-37: module references __file__
javabridge.__pycache__._javabridge.cpython-37: module references __file__
javabridge.__pycache__.jutil.cpython-37: module MAY be using inspect.stack
creating dist
creating 'dist/javabridge-1.0.18.post16+gc7ccaed-py3.7-macosx-10.7-x86_64.egg' and adding 'build/bdist.macosx-10.7-x86_64/egg' to it
removing 'build/bdist.macosx-10.7-x86_64/egg' (and everything under it)
Processing javabridge-1.0.18.post16+gc7ccaed-py3.7-macosx-10.7-x86_64.egg
creating /anaconda3/lib/python3.7/site-packages/javabridge-1.0.18.post16+gc7ccaed-py3.7-macosx-10.7-x86_64.egg
Extracting javabridge-1.0.18.post16+gc7ccaed-py3.7-macosx-10.7-x86_64.egg to /anaconda3/lib/python3.7/site-packages
Adding javabridge 1.0.18.post16+gc7ccaed to easy-install.pth file

Installed /anaconda3/lib/python3.7/site-packages/javabridge-1.0.18.post16+gc7ccaed-py3.7-macosx-10.7-x86_64.egg
Processing dependencies for javabridge==1.0.18.post16+gc7ccaed
Searching for numpy==1.16.4
Best match: numpy 1.16.4
Adding numpy 1.16.4 to easy-install.pth file
Installing f2py script to //anaconda3/bin
Installing f2py3 script to //anaconda3/bin
Installing f2py3.7 script to //anaconda3/bin

Using /anaconda3/lib/python3.7/site-packages
Finished processing dependencies for javabridge==1.0.18.post16+gc7ccaed
```

Do you have any thoughts on how I can get javabridge installed on macOS Mojave?

**Comment by mahsheed** [comment]
I am seeing the same issue on my MacOS Mojave. Haven't found a workaround yet...
```
$ pip install --no-cache-dir javabridge
Collecting javabridge
  Downloading https://files.pythonhosted.org/packages/a6/a0/c59bccabed99b1d4ac68166c59c679b375bfca75b78688b52c541b711578/javabridge-1.0.18.tar.gz (1.3MB)
     |████████████████████████████████| 1.3MB 1.6MB/s 
Requirement already satisfied: numpy in /Users/parha/.pyenv/versions/3.7.3/envs/test/lib/python3.7/site-packages (from javabridge) (1.16.2)
Installing collected packages: javabridge
    Running setup.py install for javabridge ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/parha/.pyenv/versions/3.7.3/envs/test/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/92/lg8999qx4qb08hydgys_gxzn4_dx15/T/pip-install-gnh_k5o6/javabridge/setup.py'"'"'; __file__='"'"'/private/var/folders/92/lg8999qx4qb08hydgys_gxzn4_dx15/T/pip-install-gnh_k5o6/javabridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/92/lg8999qx4qb08hydgys_gxzn4_dx15/T/pip-record-5iwjz7pd/install-record.txt --single-version-externally-managed --compile --install-headers /Users/parha/.pyenv/versions/3.7.3/envs/test/include/site/python3.7/javabridge
         cwd: /private/var/folders/92/lg8999qx4qb08hydgys_gxzn4_dx15/T/pip-install-gnh_k5o6/javabridge/
    Complete output (29 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/javabridge
    copying javabridge/_version.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge
    copying javabridge/jutil.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge
    copying javabridge/locate.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge
    copying javabridge/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge
    copying javabridge/wrappers.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge
    copying javabridge/noseplugin.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge
    creating build/lib.macosx-10.14-x86_64-3.7/javabridge/tests
    copying javabridge/tests/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_cpython.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_javabridge.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_jutil.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge/tests
    copying javabridge/tests/test_wrappers.py -> build/lib.macosx-10.14-x86_64-3.7/javabridge/tests
    creating build/lib.macosx-10.14-x86_64-3.7/javabridge/jars
    copying javabridge/jars/rhino-1.7R4.jar -> build/lib.macosx-10.14-x86_64-3.7/javabridge/jars
    copying javabridge/jars/runnablequeue.jar -> build/lib.macosx-10.14-x86_64-3.7/javabridge/jars
    copying javabridge/jars/cpython.jar -> build/lib.macosx-10.14-x86_64-3.7/javabridge/jars
    copying javabridge/jars/test.jar -> build/lib.macosx-10.14-x86_64-3.7/javabridge/jars
    running build_ext
    javac -source 6 -target 6 /private/var/folders/92/lg8999qx4qb08hydgys_gxzn4_dx15/T/pip-install-gnh_k5o6/javabridge/java/org/cellprofiler/runnablequeue/RunnableQueue.java
    warning: [options] bootstrap class path not set in conjunction with -source 6
    error: Source option 6 is no longer supported. Use 7 or later.
    error: Target option 6 is no longer supported. Use 7 or later.
    error: command 'javac' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/parha/.pyenv/versions/3.7.3/envs/test/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/92/lg8999qx4qb08hydgys_gxzn4_dx15/T/pip-install-gnh_k5o6/javabridge/setup.py'"'"'; __file__='"'"'/private/var/folders/92/lg8999qx4qb08hydgys_gxzn4_dx15/T/pip-install-gnh_k5o6/javabridge/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/92/lg8999qx4qb08hydgys_gxzn4_dx15/T/pip-record-5iwjz7pd/install-record.txt --single-version-externally-managed --compile --install-headers /Users/parha/.pyenv/versions/3.7.3/envs/test/include/site/python3.7/javabridge Check the logs for full command output.
```

**Comment by LeeKamentsky** [comment]
I have a feeling I fixed this in 16d6c91. Can you try installing from source (e.g. pip install git+https://github.com/LeeKamentsky/python-javabridge.git#egg=javabridge)?

**Comment by mahsheed** [comment]
I downgraded to Java 1.8 before seeing this and it worked. I will try your solution later and let you know how it works

**Comment by Gaara3** [comment]
> I have a feeling I fixed this in [16d6c91](https://github.com/LeeKamentsky/python-javabridge/commit/16d6c91c3aa9dbf8c80de1fc442aca696a6197fa). Can you try installing from source (e.g. `pip install git+https://github.com/LeeKamentsky/python-javabridge.git#egg=javabridge`)?

Hi Lee!I tried your method and it works!But another issue is that the version number after installation was set to be 0.0.0(instead of 1.0.14).Is there anyway to change the version number?Thanks a lot!

**Comment by LeeKamentsky** [comment]
Glad it worked for you. Probably way past time to cut another version and post to PyPi - when I do that, the version number will be better. Until I do that, unfortunately, it will display wrong unless you want to find `javabridge._version.py` and edit it by hand. The directory can be found like this, I think:

```
python -c "import javabridge._version;print(javabridge._version.__file__)"
```

**Comment by danielsiwiec** [comment]
@LeeKamentsky I still receive this error when installing 1.0.19. Running `pip install git+https://github.com/LeeKamentsky/python-javabridge.git#egg=javabridge` works fine, though. Any ideas what's causing this?

**Comment by danielsiwiec** [comment]
Upon further analysis, it appears my problem is related to #183 and has been fixed in main, but is not released yet. Any plans to cut a release including this?
